services:
  keycloak:
    image: quay.io/keycloak/keycloak:latest
    environment:
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
    ports:
      - 8080:8080
    command:
      - start-dev
    networks:
      - foodme
  postgres:
    image: postgres:16
    environment:
      POSTGRES_PASSWORD: postgres
    networks:
      - foodme
  foodme:
    build: ../../.
    environment:
      LOG_LEVEL: debug
      DESTINATION_HOST: postgres
      DESTINATION_PORT: 5432
      DESTINATION_DATABASE_TYPE: postgres
      DESTINATION_USERNAME: postgres
      DESTINATION_PASSWORD: postgres
      DESTINATION_LOG_UPSTREAM: true
      DESTINATION_LOG_DOWNSTREAM: true
      PORT: 2099
    ports:
      - 5432:2099
    networks:
      - foodme

networks:
  foodme:
    name: foodme