services:
  keycloak:
    image: quay.io/keycloak/keycloak:latest
    environment:
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
      KC_HOSTNAME: keycloak
    ports:
      - 8080:8080
    command:
      - start-dev
    networks:
      - foodme
  postgres:
    image: postgres:16
    environment:
      POSTGRES_PASSWORD: postgres
    networks:
      - foodme
  foodme:
    build: ../../.
    environment:
      LOG_LEVEL: debug
      DESTINATION_HOST: postgres
      DESTINATION_PORT: 5432
      DESTINATION_DATABASE_TYPE: postgres
      DESTINATION_USERNAME: postgres
      DESTINATION_PASSWORD: postgres
      DESTINATION_LOG_UPSTREAM: true
      DESTINATION_LOG_DOWNSTREAM: true
      PORT: 2099
      OIDC_ENABLED: true
      OIDC_CLIENT_ID: pg-access
      OIDC_CLIENT_SECRET: 'secret'
      OIDC_TOKEN_URL: http://keycloak:8080/realms/master/protocol/openid-connect/token
      OIDC_USER_INFO_URL: http://keycloak:8080/realms/master/protocol/openid-connect/userinfo
      OIDC_DATABASE_FALLBACK_TO_BASE_CLIENT: true
      OIDC_POST_AUTH_SQL_TEMPLATE: /scripts/auth.sql
      OIDC_ASSUME_USER_SESSION: true
      OIDC_ASSUME_USER_SESSION_USERNAME_CLAIM: preferred_username
      API_PORT: 10000
    ports:
      - 5432:2099
      - 10000:10000
    volumes:
      - type: bind
        source: ./auth.sql
        target: /scripts/auth.sql
    networks:
      - foodme

networks:
  foodme:
    name: foodme